services:
  talk-deck:
    build: .
    container_name: cassa-talks-tart
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
