# -*- coding: utf-8 -*-
"""TART_Stimela_Pythonized_ECDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXENGADRnDb_c1_B8QjkvCq8ZEOyp33S

# TART IUB — the Stimela imaging recipe, **purely Pythonized**

This notebook re-implements the **entire** Stimela `tart-image` recipe
(`tart_dl.yaml` in `all_recipes.txt`) in plain Python — no Stimela, no CASA,
no WSClean container. Every *logical* step that Stimela performs is done here
in NumPy/Matplotlib, with a comment header on each cell naming the Stimela
step (`cab`) it reproduces.

The science core (calibration -> dirty image -> catalog overlay -> peak check)
is the proven, correctly-aligned pipeline from
`TART_Python_Imaging_Aligned.ipynb`. On top of that we add the Stimela steps
the Aligned notebook left out: directory setup, raw-data download, Measurement-
Set construction, the MODEL column + model-source catalog, observatory rename,
flag backup, UV-coverage and antenna-layout plots, `listobs`, the **gaincal
amplitude/phase *solve*** (the Aligned notebook only *applies* gains — it never
solves for them), gain-table plots, Briggs weighting, a Cotton-Schwab
(major/minor cycle) CLEAN with `mgain`/`auto-mask`, and a FITS export.

### Stimela `tart-image` flow -> Python cell

| Stimela step (`cab`) | Python cell below |
|---|---|
| `initimgdir ... initmsdir` (`mkdir`) | **2** create directories |
| `download-hdf` (`tart-download-data`) | **4** fetch + cache raw data |
| `create-ms` (`tart2ms`) | **5** build in-memory MS, rephase note |
| `create-ms` `add-model` / `write-model-catalog` | **6** MODEL column + catalog |
| `updateobservatory` (`update-observatory-name`) | **7** observatory rename |
| `flagsave` (`casa.flagmanager`) | **8** FLAG + saved 'ORIGINAL' |
| `plotuv` (`casa.plotms`) | **9** UV-coverage |
| `plotants` (`casa.plotants`) | **10** antenna layout |
| `lister` (`casa.listobs`) | **11** observation summary |
| `calibrate_amplitude` (`casa.gaincal` `calmode=a`) | **12** StefCal amplitude solve -> G0a |
| `plotcaltable_amp` (`casa.plotms`) | **13** gain-amplitude plot |
| `calibrate_phase` (`casa.gaincal` `calmode=p`) | **14** StefCal phase solve -> G0p |
| `plotcaltable_phase` (`casa.plotms`) | **15** gain-phase plot |
| `flagfaults` (`casa.flagdata`, *disabled*) | **16** optional manual flag |
| `applycal` (`casa.applycal`) | **17** apply gains -> CORRECTED |
| `snapshotimage` (`wsclean weight briggs`) | **18** Briggs weighting |
| `snapshotimage` (`wsclean` dirty + PSF) | **19** weighted direct-DFT image |
| `snapshotimage` (`wsclean` niter/mgain/auto-mask) | **20** Cotton-Schwab CLEAN + restore |
| `casa.exportfits` / wsclean FITS output | **21** FITS export |

### The one calibration lesson carried over from the Aligned notebook
The IUB station has **4 dead antennas** and gain magnitudes from ~0.10 to ~2.07.
Dividing visibilities by tiny gain magnitudes amplifies noise and makes fake
peaks. Stimela's `gaincal` avoids this with `solnorm=true` (normalise the mean
amplitude) plus flagging; the Aligned notebook avoids it by applying **phase
only**. Both philosophies are implemented here and selectable via `CAL_SOURCE`.
The array is coplanar (all `z = 0`) so the `w`-term is identically zero.
"""

# ===========================================================================
# STIMELA  ->  opts{} block  +  recipe `tart-image` inputs / assign
# ---------------------------------------------------------------------------
# tart_dl.yaml declares the station name, the four output directories, and
# `assign: api = https://api.elec.ac.nz/tart/{recipe.tart}`. The gaincal and
# wsclean parameters live in the recipe `steps`. We gather them all here.
# ===========================================================================
import os, json, glob
import requests
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors

# --- recipe.tart  +  assign.api -------------------------------------------
TART           = "bd-iub"
API_SERVER     = "https://api.elec.ac.nz/tart/" + TART          # recipe.api
CATALOG_SERVER = "https://tart.elec.ac.nz/catalog/catalog"
ANT_RAW_URL    = "https://raw.githubusercontent.com/cassaiub/tart/main/bd-iub_processed_antenna_positions.json"

# --- output directories (the four `mkdir` steps) --------------------------
IMGDIR        = "img"          # recipe.imgdir
H5DIR         = "rawdata"      # recipe.h5dir
CAL_TABLE_DIR = "caltables"    # recipe.cal_table_dir
MSDIR         = "msdir"        # recipe.msdir

# --- observing constants ---------------------------------------------------
FREQ_HZ    = 1.57542e9                 # GPS L1
WAVELENGTH = 299792458.0 / FREQ_HZ

# --- gaincal parameters (calibrate_amplitude / calibrate_phase) -----------
SOLINT_AMP   = "300s"     # amplitude solution interval
SOLINT_PHASE = "10s"      # phase solution interval
MINSNR       = 1.0e-10    # gaincal minsnr (keep effectively every solution)
SOLNORM      = True       # gaincal solnorm=true (normalise mean |gain| -> 1)

# --- wsclean parameters (snapshotimage step) -------------------------------
IMSIZE     = 1024         # wsclean size
SCALE_ASEC = 600.0        # wsclean scale = 600asec
WEIGHTING  = "briggs"     # wsclean weight: briggs 0.0
ROBUST     = 0.0
NITER      = 5000         # wsclean niter
MGAIN      = 0.95         # wsclean mgain (major-cycle loop gain)
GAIN       = 0.1          # wsclean gain  (minor-cycle loop gain)
AUTO_MASK  = 5.0          # wsclean auto-mask (sigma)
POL        = "RR"         # wsclean pol

# --- which gains the applycal step uses ------------------------------------
#   "solved"    : the per-antenna gains we solve below with StefCal
#                 (the literal Stimela path: gaincal -> applycal).
#   "api-phase" : TART's published online gains, PHASE ONLY -- the path proven
#                 to align in TART_Python_Imaging_Aligned.ipynb and the most
#                 robust choice on this array (never divides by gain magnitude).
CAL_SOURCE = "api-phase"
#CAL_SOURCE = "solved"
GAIN_FLOOR = 0.5          # antennas with |gain| below this are treated as dead

# --- imaging grid (all-sky zenith SIN image; analog of wsclean size/scale) -
NG         = 512          # (l, m) grid; raise toward IMSIZE for finer images
EL_MIN_DEG = 5.0          # ignore satellites below this elevation in overlays

print("Equivalent wsclean field:", round(SCALE_ASEC * IMSIZE / 3600.0, 1),
      "deg across; our exact-DFT imager spans the full (l,m) unit disk.")

# ===========================================================================
# STIMELA STEPS:  initimgdir / initdatadownloaddir / initdatacaltabledir /
#                 initmsdir          (cab: mkdir  ->  /bin/mkdir -p)
# ---------------------------------------------------------------------------
# Stimela runs `mkdir -p` four times to lay out the working tree before any
# data is written. Pure Python:
# ===========================================================================
for d in (IMGDIR, H5DIR, CAL_TABLE_DIR, MSDIR):
    os.makedirs(d, exist_ok=True)
print("Created / verified:", [IMGDIR, H5DIR, CAL_TABLE_DIR, MSDIR])

# ===========================================================================
# ARRAY GEOMETRY  (used by create-ms for the UVW column, by plotants, and by
# the imager). In Stimela the ANTENNA subtable is filled by tart2ms from the
# HDF5 metadata; here we load the calibrated IUB antenna ENU positions.
# Priority: local file -> GitHub raw -> embedded fallback.
# ===========================================================================
ANT_FALLBACK = [[-0.028, 0.345, 0.0], [0.075, 0.878, 0.0], [0.33, 1.177, 0.0], [0.632, 1.322, 0.0], [0.952, 1.366, 0.0], [0.309, 0.141, 0.0], [0.849, 0.206, 0.0], [1.212, 0.056, 0.0], [1.44, -0.189, 0.0], [1.577, -0.48, 0.0], [0.218, -0.244, 0.0], [0.445, -0.738, 0.0], [0.411, -1.13, 0.0], [0.251, -1.422, 0.0], [0.014, -1.642, 0.0], [-0.177, -0.277, 0.0], [-0.574, -0.647, 0.0], [-0.956, -0.74, 0.0], [-1.286, -0.68, 0.0], [-1.57, -0.527, 0.0], [-0.328, 0.088, 0.0], [-0.803, 0.353, 0.0], [-1.007, 0.688, 0.0], [-1.052, 1.021, 0.0]]

ant_pos = None
try:
    with open("bd-iub_processed_antenna_positions.json") as f:
        ant_pos = np.array(json.load(f)["antenna_positions"])
        print("Antenna positions: local file.")
except FileNotFoundError:
    try:
        r = requests.get(ANT_RAW_URL, timeout=20); r.raise_for_status()
        ant_pos = np.array(r.json()["antenna_positions"])
        print("Antenna positions: GitHub raw.")
    except Exception as e:
        ant_pos = np.array(ANT_FALLBACK)
        print("Antenna positions: embedded fallback (", e, ").")
N_ANT = len(ant_pos)
print("Loaded", N_ANT, "antennas (ENU metres). Coplanar:",
      np.allclose(ant_pos[:, 2], 0.0), "-> w-term is zero.")

# ===========================================================================
# STIMELA STEP:  download-hdf      (cab: tart-download-data)
#   params: api, vis=true, n=raw_data_nfile(=10), dir=h5dir
# ---------------------------------------------------------------------------
# tart-download-data pulls N raw visibility HDF5 files from the TART REST API
# into rawdata/. The identical correlator visibilities are served ready-parsed
# by the REST endpoints, so we fetch those directly and cache the JSON payload
# into rawdata/ (our "downloaded files"). We also grab the live gain table and
# the satellite catalog evaluated AT the snapshot timestamp (so the modelled
# sky matches the snapshot).
# ===========================================================================
mode = requests.get(API_SERVER + "/api/v1/mode/current", timeout=30).json()
if mode.get("mode") != "vis":
    raise RuntimeError("Telescope not in visibility mode (mode=" + str(mode.get("mode")) + ").")

gains_json      = requests.get(API_SERVER + "/api/v1/calibration/gain", timeout=30).json()
visibility_data = requests.get(API_SERVER + "/api/v1/imaging/vis",      timeout=30).json()
info            = requests.get(API_SERVER + "/api/v1/info",             timeout=30).json()["info"]

timestamp = visibility_data["timestamp"]
loc = info["location"]; LAT, LON, ALT = loc["lat"], loc["lon"], loc["alt"]

sat_url = (CATALOG_SERVER + "?lat=" + str(LAT) + "&lon=" + str(LON) +
           "&alt=" + str(ALT) + "&date=" + str(timestamp))
sat_pos = requests.get(sat_url, timeout=30).json()

raw_name = os.path.join(H5DIR, "vis_" + str(timestamp).replace(":", "-") + ".json")
with open(raw_name, "w") as f:
    json.dump({"vis": visibility_data, "gain": gains_json, "info": info}, f)

print("Snapshot @", timestamp)
print("Station   :", info.get("name"), "(", round(LAT, 4), round(LON, 4), ALT, "m )")
print("Visibilities:", len(visibility_data["data"]),
      "  Satellites above horizon:", len(sat_pos))
print("Cached raw payload ->", raw_name)

# ===========================================================================
# STIMELA STEP:  create-ms      (cab: tart2ms)
#   params: hdf=GLOB(rawdata/*.hdf), ms=msdir/bd-iub.ms, clobber=true,
#           rephase=obs-midpoint, uncalibrated=false,
#           skip-celestial-source-catalog=true
# ---------------------------------------------------------------------------
# tart2ms turns the raw HDF5 visibilities into a CASA Measurement Set: it
# builds the ANTENNA / SPECTRAL_WINDOW / FIELD subtables, derives the UVW
# coordinates from the antenna layout, and writes the DATA column. We build the
# same structures in memory as NumPy arrays (our "MS" dict).
#
# rephase=obs-midpoint: every integration is phase-rotated to a common phase
# centre = the zenith at the observation midpoint. For a single snapshot the
# phase centre is just the zenith at `timestamp`, i.e. (l, m) = (0, 0) of our
# image -- exactly the convention the overlay uses
# (l = cos(el) sin(az), m = cos(el) cos(az)).
# ===========================================================================
ANT1, ANT2, UVW_M, DATA = [], [], [], []
for d in visibility_data["data"]:
    i, j = d["i"], d["j"]
    ANT1.append(i); ANT2.append(j)
    UVW_M.append(ant_pos[j] - ant_pos[i])     # ENU baseline (metres); w = 0 (coplanar)
    DATA.append(d["re"] + 1j * d["im"])       # raw correlator visibility (DATA column)
ANT1 = np.array(ANT1); ANT2 = np.array(ANT2)
UVW_M = np.array(UVW_M)
UVW_WL = UVW_M / WAVELENGTH                    # UVW in wavelengths
DATA = np.array(DATA)
U, V = UVW_WL[:, 0], UVW_WL[:, 1]              # w ~ 0

ms = {"ANTENNA1": ANT1, "ANTENNA2": ANT2, "UVW": UVW_M, "U": U, "V": V,
      "DATA": DATA, "FREQ": FREQ_HZ, "TIME": timestamp,
      "PHASE_CENTRE": "zenith@" + str(timestamp), "TELESCOPE_NAME": TART}

print("Built in-memory MS:", len(DATA), "rows (baselines),", N_ANT,
      "antennas, 1 channel @", FREQ_HZ / 1e9, "GHz")
print("Max baseline:", round(float(np.hypot(U, V).max()), 1), "wavelengths")

# ===========================================================================
# STIMELA STEP:  create-ms (continued)  ->  add-model + write-model-catalog
#   tart2ms params: add-model=true, write-model-catalog=true,
#                   model-catalog-name-prefix=msdir/model_sources_
# ---------------------------------------------------------------------------
# add-model=true fills MODEL_DATA with the predicted visibilities of the known
# sources (the GPS satellites above the horizon); write-model-catalog dumps the
# source list to disk. gaincal then solves the antenna gains by comparing DATA
# against MODEL_DATA.
#
# Sky model = the catalog satellites as equal-flux point sources at their
# direction cosines. The point-source model visibility uses the SAME sign
# convention as our imager, so that after calibration  corrected DATA ~ MODEL
# and the image peaks land on the catalog positions:
#     MODEL_ij = sum_s flux_s * exp(-2*pi*i (u l_s + v m_s))
# ===========================================================================
def sat_lm(s):
    az, el = np.radians(s["az"]), np.radians(s["el"])
    return np.cos(el) * np.sin(az), np.cos(el) * np.cos(az)   # l=East, m=North

visible = [s for s in sat_pos if s["el"] >= EL_MIN_DEG]
satlm = np.array([sat_lm(s) for s in visible]) if visible else np.zeros((0, 2))
model_flux = np.ones(len(visible))

if len(visible):
    ph = -2 * np.pi * (np.outer(U, satlm[:, 0]) + np.outer(V, satlm[:, 1]))   # (Nbl, Nsat)
    MODEL = (np.exp(1j * ph) * model_flux).sum(axis=1)
else:
    MODEL = np.zeros_like(DATA)
ms["MODEL"] = MODEL

cat_path = os.path.join(MSDIR, "model_sources_" + TART + ".txt")
with open(cat_path, "w") as f:
    f.write("# name az_deg el_deg l m flux\n")
    for s, (l, m) in zip(visible, satlm):
        f.write(str(s.get("name", "src")) + " " + str(round(s["az"], 3)) + " " +
                str(round(s["el"], 3)) + " " + str(round(float(l), 5)) + " " +
                str(round(float(m), 5)) + " 1.0\n")
print("MODEL_DATA built from", len(visible), "satellites; catalog ->", cat_path)

# ===========================================================================
# STIMELA STEP:  updateobservatory   (cab: update-observatory-name)
#   command: taql "UPDATE {vis}::OBSERVATION SET TELESCOPE_NAME='MeerKAT'"
# ---------------------------------------------------------------------------
# Stimela rewrites the OBSERVATION subtable so downstream CASA / wsclean tasks
# treat the data as a known observatory (MeerKAT) and accept it without
# complaint. It is a metadata-only change -- the visibilities are untouched.
# ===========================================================================
ms["TELESCOPE_NAME"] = "MeerKAT"
print("OBSERVATION.TELESCOPE_NAME set to", ms["TELESCOPE_NAME"], "(metadata only).")

# ===========================================================================
# STIMELA STEP:  flagsave   (cab: casa.flagmanager, mode=save, versionname=ORIGINAL)
# ---------------------------------------------------------------------------
# flagmanager snapshots the FLAG column so it can be restored later. The real
# flagging on the IUB array is the dead antennas: 4 antennas have |gain| ~ 0.
# We build a per-baseline FLAG (True = flagged) from the published gain
# magnitudes and save the 'ORIGINAL' flag version.
# ===========================================================================
gain_mag   = np.array(gains_json["gain"])
gain_phase = np.array(gains_json["phase_offset"])
dead       = np.where(gain_mag < 1e-6)[0]
ant_good   = gain_mag >= 1e-6                       # boolean per antenna

FLAG = (~ant_good[ANT1]) | (~ant_good[ANT2])        # baselines touching a dead antenna
flagversions = {"ORIGINAL": FLAG.copy()}            # the saved 'ORIGINAL' version

print("Dead antennas (|gain|~0):", list(dead))
print("Gain magnitudes:", np.round(gain_mag, 2))
print("Flagged baselines:", int(FLAG.sum()), "of", len(FLAG),
      "(saved flag version 'ORIGINAL')")

# ===========================================================================
# STIMELA STEP:  plotuv   (cab: casa.plotms, xaxis=U, yaxis=V)  -> msdir/UV.png
# ---------------------------------------------------------------------------
# Snapshot UV-coverage. A real MS is Hermitian, so each baseline is plotted
# together with its conjugate (-u, -v). (Omitted in the Aligned notebook.)
# ===========================================================================
keep = ~FLAG
plt.figure(figsize=(7, 7), dpi=120)
plt.scatter(U[keep],  V[keep],  s=12, c="navy")
plt.scatter(-U[keep], -V[keep], s=12, c="navy", alpha=0.5)
if FLAG.any():
    plt.scatter(U[FLAG],  V[FLAG],  s=12, c="red", alpha=0.5, label="flagged")
    plt.scatter(-U[FLAG], -V[FLAG], s=12, c="red", alpha=0.5)
    plt.legend(loc="upper right")
plt.axhline(0, lw=0.5, color="gray"); plt.axvline(0, lw=0.5, color="gray")
plt.gca().set_aspect("equal")
plt.xlabel("u (wavelengths)"); plt.ylabel("v (wavelengths)")
plt.title("UV-coverage  -  " + TART + "  @ " + str(timestamp))
plt.tight_layout()
plt.savefig(os.path.join(MSDIR, "UV.png"), dpi=120); plt.show()

# ===========================================================================
# STIMELA STEP:  plotants   (cab: casa.plotants)  -> msdir/antconfig.png
# ---------------------------------------------------------------------------
# Antenna layout in the local ENU plane, dead antennas marked. (Omitted in the
# Aligned notebook.)
# ===========================================================================
plt.figure(figsize=(7, 7), dpi=120)
plt.scatter(ant_pos[ant_good, 0], ant_pos[ant_good, 1], s=80, c="seagreen", label="live")
if len(dead):
    plt.scatter(ant_pos[dead, 0], ant_pos[dead, 1], s=90, c="red", marker="x", label="dead")
for k, (x, y, _) in enumerate(ant_pos):
    plt.text(x + 0.03, y + 0.03, str(k), fontsize=8)
plt.gca().set_aspect("equal")
plt.xlabel("East (m)"); plt.ylabel("North (m)")
plt.title("Antenna configuration  -  " + TART)
plt.legend(loc="upper right"); plt.tight_layout()
plt.savefig(os.path.join(MSDIR, "antconfig.png"), dpi=120); plt.show()

# ===========================================================================
# STIMELA STEP:  lister   (cab: casa.listobs)
# ---------------------------------------------------------------------------
# listobs prints a human-readable summary of the MS. Pure-Python version:
# ===========================================================================
print("=============== listobs (Python) ===============")
print("Telescope      :", ms["TELESCOPE_NAME"], "(true array: TART", TART + ")")
print("Observation    :", timestamp)
print("Phase centre   :", ms["PHASE_CENTRE"], "(zenith)")
print("Location       : lat", round(LAT, 4), "lon", round(LON, 4), "alt", ALT, "m")
print("Antennas       :", N_ANT, "(", int(ant_good.sum()), "live,", len(dead), "dead )")
print("Baselines      :", len(DATA), "(", int((~FLAG).sum()), "unflagged )")
print("Spectral window: 1 channel, freq", FREQ_HZ / 1e9, "GHz, lambda",
      round(WAVELENGTH, 4), "m")
print("Fields         : 1 (zenith snapshot)")
print("Polarization   :", POL, "(TART is effectively single-pol)")
print("================================================")

# ===========================================================================
# STIMELA STEP:  calibrate_amplitude   (cab: casa.gaincal)
#   params: gaintype=G, calmode=a, solnorm=true, solint=300s, minsnr=1e-10
#           caltable = caltables/tart.G0a
# ---------------------------------------------------------------------------
# gaincal solves per-antenna complex gains g_p from
#     DATA_pq = g_p * conj(g_q) * MODEL_pq           (antenna-based least squares)
# We implement the StefCal alternating-least-squares solver (Salvini &
# Wijnholds 2014). calmode='a' keeps only the AMPLITUDE; solnorm=true
# normalises the mean amplitude to 1 -- this is exactly what stops a low-gain
# antenna from blowing up, the failure mode diagnosed in the Aligned notebook.
# solint=300s over a single snapshot -> one solution per antenna.
#
# NOTE: the Aligned notebook only *applies* gains from the API; it never solves
# for them. This cell is the solve step Stimela does and the Aligned notebook
# omits.
# ===========================================================================
def stefcal(d, m, a1, a2, n_ant, good, n_iter=100, tol=1e-8):
    # solve d_pq = g_p conj(g_q) m_pq for complex g (uses each baseline + conjugate)
    p  = np.concatenate([a1, a2]);     q  = np.concatenate([a2, a1])
    dd = np.concatenate([d, np.conj(d)]); mm = np.concatenate([m, np.conj(m)])
    ok = good[p] & good[q] & (np.abs(mm) > 0)
    p, q, dd, mm = p[ok], q[ok], dd[ok], mm[ok]
    g = np.ones(n_ant, dtype=complex)
    for _ in range(n_iter):
        z   = np.conj(g[q]) * mm                       # predictor for g_p
        num = np.zeros(n_ant, dtype=complex)
        den = np.zeros(n_ant)
        np.add.at(num, p, dd * np.conj(z))
        np.add.at(den, p, (z * np.conj(z)).real)
        gnew = np.where(den > 0, num / np.where(den > 0, den, 1.0), g)
        gnew[~good] = 0.0
        gmix = 0.5 * (g + gnew)                         # damped (even) StefCal step
        if np.linalg.norm(gmix - g) <= tol * max(np.linalg.norm(gmix), 1e-12):
            g = gmix; break
        g = gmix
    return g

g_full = stefcal(DATA, MODEL, ANT1, ANT2, N_ANT, ant_good)
G0a = np.abs(g_full)                                    # calmode='a' -> amplitude only
if SOLNORM and np.any(ant_good):
    G0a = G0a / np.mean(G0a[ant_good])                  # solnorm=true
G0a[~ant_good] = 0.0
np.savez(os.path.join(CAL_TABLE_DIR, "tart.G0a.npz"), gain=G0a, ant_good=ant_good)
print("Solved amplitude gains G0a (solnorm, mean of live = 1):")
print(np.round(G0a, 3))

# ===========================================================================
# STIMELA STEP:  plotcaltable_amp   (cab: casa.plotms on tart.G0a)
#   xaxis=antenna1, yaxis=gainamp   -> caltables/gainamp.tart.png
# ===========================================================================
plt.figure(figsize=(8, 4), dpi=120)
xs = np.arange(N_ANT)
plt.bar(xs[ant_good], G0a[ant_good], color="steelblue", label="solved |gain|")
if len(dead):
    plt.scatter(dead, np.full(len(dead), 0.02), c="red", marker="x", s=60, label="dead/flagged")
plt.axhline(1.0, color="gray", lw=0.8, ls="--", label="solnorm mean = 1")
plt.xlabel("antenna"); plt.ylabel("gain amplitude")
plt.title("G0a  -  amplitude calibration"); plt.legend(); plt.tight_layout()
plt.savefig(os.path.join(CAL_TABLE_DIR, "gainamp.tart.png"), dpi=120); plt.show()

# ===========================================================================
# STIMELA STEP:  calibrate_phase   (cab: casa.gaincal)
#   params: gaintype=G, calmode=p, solint=10s, minsnr=1e-10,
#           gaintable=[tart.G0a]   (G0a applied on the fly)
#           caltable = caltables/tart.G0p
# ---------------------------------------------------------------------------
# The phase solve runs with the amplitude table applied on the fly: divide DATA
# by (G0a_p * G0a_q), StefCal again, and keep only the PHASE (calmode='p').
# Splitting bounded amplitude then phase is the same discipline the Aligned
# notebook arrived at: phases set source positions; amplitudes are normalised
# so they cannot amplify noise.
# ===========================================================================
amp_pq = np.where(ant_good[ANT1] & ant_good[ANT2], G0a[ANT1] * G0a[ANT2], 1.0)
DATA_ampcal = np.where(amp_pq > 0, DATA / np.where(amp_pq > 0, amp_pq, 1.0), DATA)

g_phase = stefcal(DATA_ampcal, MODEL, ANT1, ANT2, N_ANT, ant_good)
G0p = np.exp(1j * np.angle(g_phase))                    # calmode='p' -> phase only
G0p[~ant_good] = 0.0
np.savez(os.path.join(CAL_TABLE_DIR, "tart.G0p.npz"),
         phase=np.angle(g_phase), ant_good=ant_good)
print("Solved phase gains G0p (degrees):")
print(np.round(np.degrees(np.angle(g_phase)), 1))

# ===========================================================================
# STIMELA STEP:  plotcaltable_phase   (cab: casa.plotms on tart.G0p)
#   xaxis=time, yaxis=gainphase, iteraxis=antenna -> caltables/gainphase.tart.png
# ---------------------------------------------------------------------------
# Cross-check: overlay TART's PUBLISHED online phase solution (from the REST
# gain table) on our StefCal phases. They should track up to an unobservable
# global reference phase, which we remove using the first live antenna.
# ===========================================================================
ref       = np.where(ant_good)[0][0]
solved_ph = np.degrees(np.angle(g_phase))
api_ph    = np.degrees(gain_phase)
solved_ph = ((solved_ph - solved_ph[ref] + 180) % 360) - 180
api_aln   = ((api_ph    - api_ph[ref]    + 180) % 360) - 180

plt.figure(figsize=(8, 4), dpi=120)
xs = np.arange(N_ANT)[ant_good]
plt.plot(xs, solved_ph[ant_good], "o-", label="StefCal G0p")
plt.plot(xs, api_aln[ant_good],   "s--", alpha=0.7, label="TART API phase")
plt.xlabel("antenna"); plt.ylabel("gain phase (deg, ref-subtracted)")
plt.title("G0p  -  phase calibration"); plt.legend(); plt.tight_layout()
plt.savefig(os.path.join(CAL_TABLE_DIR, "gainphase.tart.png"), dpi=120); plt.show()

# ===========================================================================
# STIMELA STEP:  flagfaults   (cab: casa.flagdata, antenna='6')   [DISABLED in
#                              the recipe -- the step is commented out]
# ---------------------------------------------------------------------------
# The recipe keeps a manual flag step ready but disabled. Equivalent hook:
# add antenna ids to MANUAL_FLAG_ANTS to flag every baseline touching them,
# then re-derive FLAG. Left empty to match the recipe's disabled step.
# ===========================================================================
MANUAL_FLAG_ANTS = []        # e.g. [6] to reproduce the commented `antenna: '6'`
if MANUAL_FLAG_ANTS:
    for a in MANUAL_FLAG_ANTS:
        ant_good[a] = False
    FLAG = (~ant_good[ANT1]) | (~ant_good[ANT2])
    print("Manually flagged", MANUAL_FLAG_ANTS, "-> flagged baselines:", int(FLAG.sum()))
else:
    print("No manual antenna flags (matches the disabled flagfaults step).")

# ===========================================================================
# STIMELA STEP:  applycal   (cab: casa.applycal)
#   params: gaintable=[tart.G0a, tart.G0p], flagbackup=true
# ---------------------------------------------------------------------------
# applycal writes CORRECTED_DATA = DATA / (G_p conj(G_q)). CAL_SOURCE selects
# the gains:
#   'solved'    -> G_p = G0a_p * G0p_p          (the StefCal tables above)
#   'api-phase' -> G_p = exp(i * phase_api_p)    (phase only; the proven path)
# Flagged baselines (dead antennas) are dropped, never divided by ~0.
# ===========================================================================
if CAL_SOURCE == "solved":
    G = G0a * G0p                                       # complex per-antenna gain
elif CAL_SOURCE == "api-phase":
    G = np.where(ant_good, np.exp(1j * gain_phase), 0.0)
else:
    raise ValueError(CAL_SOURCE)

denom = G[ANT1] * np.conj(G[ANT2])
valid = (~FLAG) & (np.abs(denom) > 0)
CORRECTED = np.zeros_like(DATA)
CORRECTED[valid] = DATA[valid] / denom[valid]
ms["CORRECTED"] = CORRECTED
print("applycal: CAL_SOURCE='" + CAL_SOURCE + "' ->", int(valid.sum()),
      "corrected baselines (", int((~valid).sum()), "dropped ).")

# ===========================================================================
# STIMELA STEP:  snapshotimage (part 1)  ->  wsclean `weight briggs 0.0`
# ---------------------------------------------------------------------------
# wsclean weights each visibility before imaging. Briggs/robust weighting
# interpolates between natural (robust=+2) and uniform (robust=-2). We grid the
# (u, v) samples (plus conjugates) to estimate the local density W_k per cell,
# then form  w = 1 / (1 + W_k * f2),  with
#     f2 = (5 * 10^-robust)^2 / ( sum W_k^2 / sum W_k ).
# TART's uv-coverage is sparse and non-redundant, so most cells hold a single
# sample and briggs/uniform/natural nearly coincide -- the weighting is applied
# for fidelity to wsclean rather than for a large change in the map.
# ===========================================================================
Uc, Vc, Vis = U[valid], V[valid], CORRECTED[valid]
uvmax = np.hypot(Uc, Vc).max()
ncell = 256
def cell_idx(u, v):
    iu = np.clip(((u + uvmax) / (2 * uvmax) * (ncell - 1)).astype(int), 0, ncell - 1)
    iv = np.clip(((v + uvmax) / (2 * uvmax) * (ncell - 1)).astype(int), 0, ncell - 1)
    return iu, iv
grid = np.zeros((ncell, ncell))
for (uu, vv) in [(Uc, Vc), (-Uc, -Vc)]:
    iu, iv = cell_idx(uu, vv)
    np.add.at(grid, (iu, iv), 1.0)
iu, iv = cell_idx(Uc, Vc)
Wk = grid[iu, iv]                                       # natural density at each sample
f2 = (5.0 * 10 ** (-ROBUST)) ** 2 / (np.sum(grid ** 2) / np.sum(grid))
Wbriggs = 1.0 / (1.0 + Wk * f2)
Wbriggs = Wbriggs / Wbriggs.sum()                       # normalise
print("Imaging", len(Vis), "weighted visibilities; scheme:", WEIGHTING,
      "robust", ROBUST)

# ===========================================================================
# STIMELA STEP:  snapshotimage (part 2)  ->  wsclean dirty image + PSF
# ---------------------------------------------------------------------------
# wsclean grids + FFTs the weighted visibilities to make the dirty image and
# the PSF (synthesised beam). Because the IUB array is coplanar (w = 0) we
# evaluate the measurement equation EXACTLY with a direct DFT on the (l, m)
# unit disk -- no gridding, no FFT axis ambiguity:
#     I(l, m) = sum_bl  w_bl * Re( V_bl * exp(+2*pi*i (u l + v m)) )
# (Same imager as the Aligned notebook, now visibility-weighted.)
# ===========================================================================
ax = np.linspace(-1.0, 1.0, NG)
Lg, Mg = np.meshgrid(ax, ax)
disk = (Lg ** 2 + Mg ** 2) <= 1.0

def dft_image(vis, wts):
    img = np.zeros(Lg.shape)
    for k in range(len(vis)):
        img += np.real(vis[k] * wts[k] * np.exp(2j * np.pi * (Uc[k] * Lg + Vc[k] * Mg)))
    img[~disk] = 0.0
    return img

dirty = dft_image(Vis, Wbriggs)
psf   = dft_image(np.ones_like(Vis), Wbriggs)
psf   = psf / psf.max()                                 # normalise PSF peak to 1
print("Dirty image:", NG, "x", NG, " peak =", round(float(dirty.max()), 4))

# ===========================================================================
# STIMELA STEP:  snapshotimage (part 3)  ->  wsclean deconvolution + restore
#   wsclean params: niter=5000, gain=0.1, mgain=0.95, auto-mask=5, restore on
# ---------------------------------------------------------------------------
# wsclean runs a Cotton-Schwab CLEAN: minor cycles (Hogbom) subtract scaled
# PSFs from the residual IMAGE down to mgain of the cycle peak; a major cycle
# then predicts the model visibilities, subtracts them from the data, and
# re-images the residual EXACTLY (our DFT) to clear approximation error.
# auto-mask stops cleaning at auto_mask * sigma. Finally the CLEAN model is
# convolved with a fitted Gaussian restoring beam and the residual added back.
# ===========================================================================
def robust_sigma(img):
    v = img[disk]
    return 1.4826 * np.median(np.abs(v - np.median(v)))

def degrid(model_img):
    ys, xs = np.where(model_img != 0.0)
    if len(xs) == 0:
        return np.zeros(len(Vis), dtype=complex)
    lk, mk, fk = Lg[ys, xs], Mg[ys, xs], model_img[ys, xs]
    Vm = np.zeros(len(Vis), dtype=complex)
    for n in range(len(fk)):
        Vm += fk[n] * np.exp(-2j * np.pi * (Uc * lk[n] + Vc * mk[n]))
    return Vm

cy = cx = NG // 2
sigma0 = robust_sigma(dirty)
model = np.zeros_like(dirty)
residual = dirty.copy()
n_major, n_minor, total = 8, 1000, 0
for major in range(n_major):
    cyc_peak = np.abs(residual).max()
    #stop = max(cyc_peak * (1.0 - MGAIN), AUTO_MASK * sigma0)
    stop = cyc_peak * 0.1  # Clean down to 10% of the brightest peak
    for it in range(n_minor):
        if total >= NITER:
            break
        idx = np.unravel_index(np.argmax(np.abs(residual)), residual.shape)
        pk = residual[idx]
        if abs(pk) <= stop:
            break
        amp = pk * GAIN
        model[idx] += amp
        residual -= amp * np.roll(np.roll(psf, idx[0] - cy, 0), idx[1] - cx, 1)
        total += 1
    # ---- major cycle: exact residual from the visibilities (Cotton-Schwab) --
    residual = dft_image(Vis - degrid(model), Wbriggs)
    if np.abs(residual).max() <= AUTO_MASK * sigma0 or total >= NITER:
        break
print("CLEAN:", total, "minor iterations over", major + 1, "major cycles.")

# ---- fit an elliptical Gaussian restoring beam to the PSF main lobe --------
win = 40
sub = psf[cy - win:cy + win, cx - win:cx + win]
yy, xx = np.mgrid[-win:win, -win:win]
mlobe = sub >= 0.5
wsum = sub[mlobe].sum()
sxx = (sub[mlobe] * xx[mlobe] ** 2).sum() / wsum
syy = (sub[mlobe] * yy[mlobe] ** 2).sum() / wsum
sxy = (sub[mlobe] * xx[mlobe] * yy[mlobe]).sum() / wsum
cov = np.array([[sxx, sxy], [sxy, syy]])
if mlobe.sum() < 6 or np.linalg.det(cov) <= 0:
    beam = np.exp(-0.5 * (xx * xx + yy * yy) / 9.0)     # circular fallback
else:
    inv = np.linalg.inv(cov)
    beam = np.exp(-0.5 * (xx * xx * inv[0, 0] + 2 * xx * yy * inv[0, 1] + yy * yy * inv[1, 1]))
beam_full = np.zeros_like(dirty)
beam_full[cy - win:cy + win, cx - win:cx + win] = beam

def fftconv(a, b):
    return np.real(np.fft.ifft2(np.fft.fft2(a) * np.fft.fft2(np.fft.ifftshift(b))))

restored = fftconv(model, beam_full) + residual
restored[~disk] = 0.0
print("Restored image peak =", round(float(restored.max()), 4))

# 1. Did we actually find any sources?
print("Total flux in CLEAN model map:", np.sum(model))
print("Number of non-zero CLEAN components:", np.count_nonzero(model))

# 2. What did CLEAN actually delete?
diff = dirty - restored
print("Max absolute difference removed by CLEAN:", np.max(np.abs(diff)))

# 3. Plot the "ghosts"
plt.figure(figsize=(6, 6), dpi=100)
plt.imshow(diff, extent=[-1, 1, -1, 1], origin="lower", cmap="seismic",
           norm=colors.CenteredNorm())
plt.title("What CLEAN actually deleted (Dirty - Restored)")
plt.colorbar(label="Flux removed")
plt.show()

# ===========================================================================
# STIMELA STEP:  wsclean writes FITS directly (the CASA path uses
#                casa.exportfits)   ->  img/bd-iub-image.fits
# ---------------------------------------------------------------------------
# Write the restored image to FITS with a WCS. The phase centre is the zenith
# at the snapshot time; we attach an all-sky zenithal SIN projection centred on
# the zenith RA/Dec, matching how tart2ms/wsclean label the axes.
# ===========================================================================
try:
    from astropy.io import fits
    from astropy.wcs import WCS
    from astropy.time import Time
    from astropy.coordinates import EarthLocation, AltAz, SkyCoord
    import astropy.units as u

    site = EarthLocation(lat=LAT * u.deg, lon=LON * u.deg, height=ALT * u.m)
    zen = SkyCoord(AltAz(az=0 * u.deg, alt=90 * u.deg,
                         obstime=Time(timestamp), location=site)).icrs
    w = WCS(naxis=2)
    w.wcs.crpix = [NG / 2 + 0.5, NG / 2 + 0.5]
    w.wcs.cdelt = [-np.degrees(2.0 / NG), np.degrees(2.0 / NG)]
    w.wcs.ctype = ["RA---SIN", "DEC--SIN"]
    w.wcs.crval = [zen.ra.deg, zen.dec.deg]
    hdu = fits.PrimaryHDU(data=restored.astype("float32"), header=w.to_header())
    hdu.header["BUNIT"]    = "JY/BEAM"
    hdu.header["TELESCOP"] = ms["TELESCOPE_NAME"]
    hdu.header["OBJECT"]   = TART + " zenith"
    hdu.header["DATE-OBS"] = str(timestamp)
    fits_path = os.path.join(IMGDIR, TART + "-image.fits")
    hdu.writeto(fits_path, overwrite=True)
    print("Wrote", fits_path, " (zenith RA,Dec =",
          round(zen.ra.deg, 3), round(zen.dec.deg, 3), "deg )")
except Exception as e:
    np.save(os.path.join(IMGDIR, TART + "-image.npy"), restored)
    print("astropy FITS export skipped (", e, "); saved .npy instead.")

# ===========================================================================
# RESULT:  dirty + CLEAN-restored image with the catalog satellites overlaid.
#   This is the alignment check the Aligned notebook is built around: the
#   catalog is overlaid with the IDENTITY transform (no rotation / scaling).
# ===========================================================================
fig, axs = plt.subplots(1, 2, figsize=(16, 8), dpi=120)
for axp, img, ttl in zip(axs, [dirty, restored], ["dirty image", "CLEAN restored"]):
    axp.imshow(img, extent=[-1, 1, -1, 1], origin="lower", cmap="viridis",
               norm=colors.Normalize(vmin=0, vmax=img.max()))
    for s in visible:
        l, m = sat_lm(s)
        axp.scatter(l, m, facecolors="none", edgecolors="cyan", s=130, linewidths=1.6)
        axp.text(l + 0.02, m + 0.02, str(s.get("name", ""))[:10], color="cyan", fontsize=7)
    th = np.linspace(0, 2 * np.pi, 400)
    axp.plot(np.cos(th), np.sin(th), color="gray", lw=0.8, alpha=0.6)
    axp.set_aspect("equal"); axp.set_xlim(-1, 1); axp.set_ylim(-1, 1)
    axp.set_xlabel("l (East +)"); axp.set_ylabel("m (North +)")
    axp.set_title(TART + "  " + ttl + "  (CAL_SOURCE=" + CAL_SOURCE + ")")
plt.tight_layout(); plt.show()

# ===========================================================================
# QUANTITATIVE CHECK:  do the brightest peaks coincide with catalog satellites?
#   (same test as the Aligned notebook, on the weighted dirty image)
# ===========================================================================
def local_maxima(img, radius=12, frac=0.30):
    thr, Nn, out = img.max() * frac, img.shape[0], []
    for y, x in np.argwhere((img > thr) & disk):
        y0, y1 = max(0, y - radius), min(Nn, y + radius + 1)
        x0, x1 = max(0, x - radius), min(Nn, x + radius + 1)
        if img[y, x] >= img[y0:y1, x0:x1].max() - 1e-12:
            out.append((img[y, x], Lg[y, x], Mg[y, x]))
    return sorted(out, reverse=True)

peaks = local_maxima(dirty)
print(" peak_l   peak_m    dist   nearest satellite")
print("-" * 60)
#for val, pl, pm in peaks[:10]:
for val, pl, pm in peaks:
    if len(satlm) == 0:
        break
    dd = np.hypot(satlm[:, 0] - pl, satlm[:, 1] - pm)
    k = int(np.argmin(dd))
    print(format(pl, "8.3f"), format(pm, "8.3f"), " ", format(dd[k], "6.3f"),
          " ", str(visible[k].get("name", ""))[:26],
          "(el=" + str(round(visible[k]["el"])) + ")")

# ===========================================================================
# ECDF PLOT: Cumulative distribution of peak-to-satellite distances
# ===========================================================================
# 1. Collect all the minimum distances from the previous step
distances = []
for val, pl, pm in peaks:
    if len(satlm) == 0:
        break
    dd = np.hypot(satlm[:, 0] - pl, satlm[:, 1] - pm)
    distances.append(np.min(dd))

distances = np.array(distances)

if len(distances) > 0:
    # 2. Calculate ECDF components
    x_ecdf = np.sort(distances)
    y_ecdf = np.arange(1, len(distances) + 1) / len(distances)

    # 3. Calculate percentage within a specific threshold
    threshold = 0.1  # roughly 5.7 degrees
    pct_within = np.mean(distances <= threshold) * 100

    print(f"\n--- ECDF Analysis ---")
    print(f"{pct_within:.1f}% of detected peaks fall within {threshold} directional cosine units.")

    # 4. Plot the ECDF
    plt.figure(figsize=(8, 5), dpi=120)
    plt.step(x_ecdf, y_ecdf, where='post', color='navy', linewidth=2, label='Empirical CDF')

    # Mark the individual data points
    plt.plot(x_ecdf, y_ecdf, 'o', color='navy', alpha=0.4, markersize=4)

    # Visual aides for the threshold
    plt.axvline(threshold, color='crimson', linestyle='--', alpha=0.8,
                label=f'Threshold ({threshold})')
    plt.axhline(pct_within / 100, color='seagreen', linestyle='--', alpha=0.8,
                label=f'{pct_within:.1f}% Success')

    plt.xlabel(r'Distance to Nearest Satellite (unitless $\sim$ radians)')
    plt.ylabel('Cumulative Probability')
    plt.title('ECDF of Peak-to-Satellite Distances')
    plt.grid(True, alpha=0.3)
    plt.legend(loc='lower right')
    plt.tight_layout()
    plt.show()
else:
    print("\nNo peaks detected in the image. ECDF computation aborted.")

"""## Summary — every Stimela step, in pure Python

This notebook reproduces the full `tart-image` recipe without Stimela/CASA/WSClean:

1. **`mkdir`** -> `os.makedirs` (cell 2)
2. **`tart-download-data`** -> REST fetch + cache to `rawdata/` (cell 4)
3. **`tart2ms`** -> in-memory MS arrays; `rephase=obs-midpoint` = zenith phase
   centre at the snapshot time (cell 5)
4. **`add-model` / `write-model-catalog`** -> MODEL visibilities from the
   satellite catalog + `model_sources_*.txt` (cell 6)
5. **`update-observatory-name`** -> `TELESCOPE_NAME='MeerKAT'` metadata (cell 7)
6. **`flagmanager` save** -> per-baseline `FLAG` + saved `'ORIGINAL'` (cell 8)
7. **`plotms` UV / `plotants` / `listobs`** -> cells 9-11
8. **`gaincal` amplitude (`calmode=a`, `solnorm`)** -> StefCal solve `G0a` (cell 12)
9. **`gaincal` phase (`calmode=p`)** -> StefCal solve `G0p` (cell 14)
10. **`flagdata`** (disabled in recipe) -> `MANUAL_FLAG_ANTS` hook (cell 16)
11. **`applycal`** -> `CORRECTED = DATA / (G_p conj(G_q))` (cell 17)
12. **`wsclean`** -> Briggs weighting + exact-DFT dirty image/PSF +
    Cotton-Schwab CLEAN (`niter`/`mgain`/`auto-mask`) + restore (cells 18-20)
13. **FITS output** -> astropy SIN-WCS export (cell 21)

### What was already correct in the Aligned notebook (and is kept here)
The calibration *apply*, the exact-DFT imager, the catalog overlay with the
identity transform, the peak-vs-catalog check, and the Hogbom deconvolution
(here generalised to Cotton-Schwab major/minor cycles).

### What this notebook adds (omitted by the Aligned notebook)
Directory setup, raw-data caching, the explicit MS data model + `rephase`
note, the MODEL column and model-source catalog, observatory rename, flag
versioning, UV/antenna/listobs diagnostics, the **gaincal amplitude+phase
*solve*** (StefCal — the Aligned notebook only applied gains), the gain-table
plots, Briggs weighting, the major-cycle CLEAN, and the FITS export.

### Calibration choice (`CAL_SOURCE`)
- `"api-phase"` (default): TART's published online gains, phase only — the
  robust path proven to align in `TART_Python_Imaging_Aligned.ipynb`.
- `"solved"`: image purely from the StefCal `G0a`+`G0p` we solve here — the
  literal Stimela `gaincal -> applycal` path. With `solnorm` and dead-antenna
  flagging it avoids the gain-magnitude blow-up the Aligned notebook warns about.

### For the GNN work
The imager (cell 19) is a plain differentiable linear operator
`I = Re(A . V)` with `A[bl, l, m] = exp(2pi i (u.l + v.m))`. The StefCal solver,
the model predictor (`degrid`), and the CLEAN loop are all pure NumPy and can be
swapped for / wrapped by learned modules end-to-end.
"""